DROP DATABASE IF EXISTS Online_Food_Order_Delivery;
CREATE DATABASE Online_Food_Order_Delivery;
USE Online_Food_Order_Delivery;

CREATE TABLE User (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE,
    USER_TYPE VARCHAR(50)
);

CREATE TABLE Customer (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    -- NAME VARCHAR(50),
    ADDRESS VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES User(ID)
    -- FOREIGN KEY (PASSWORD) REFERENCES User(PASSWORD) 
);

CREATE TABLE Restaurant (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    NAME VARCHAR(50),
    LOCATION VARCHAR(50),
    CUISINE_TYPE VARCHAR(50),
    RATING FLOAT(2,2),
    FOREIGN KEY (ID) REFERENCES User(ID)
    -- FOREIGN KEY (PASSWORD) REFERENCES User(PASSWORD)
);

CREATE TABLE Driver (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    -- NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES User(ID)
    -- FOREIGN KEY (PASSWORD) REFERENCES User(PASSWORD)
);

CREATE TABLE Administrator (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES User(ID)
    -- FOREIGN KEY (PASSWORD) REFERENCES User(PASSWORD)
);

DELIMITER //
CREATE TRIGGER capitalize
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    SET NEW.ADDRESS = CONCAT(UPPER(SUBSTRING(NEW.ADDRESS, 1, 1)), LOWER(SUBSTRING(NEW.ADDRESS, 2)));
END //
DELIMITER ;

INSERT INTO User(USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES ('admin', 'admin1234', "admin@gmail.com", "Admin");
-- ('frottori', 'frosso1234'),
-- ('tsosmi', 'dimitris1234'),
-- ('filegeiasou', 'aggelos1234');

SELECT * FROM USER;
SELECT * FROM CUSTOMER;
SELECT * FROM DRIVER;
SELECT * FROM RESTAURANT;

# Admins will probably just be in the database and can only sign in.
INSERT INTO ADMINISTRATOR(USERNAME, PASSWORD) VALUES ("admin", "admin1234");
